# Javascript Node CircleCI 2.0 configuration file
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
version: 2
jobs:
  digibytego:
    docker:
      - image: circleci/node:9-browsers
    working_directory: ~/digibytego
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: npm run apply:digibytego
      - run: npm run test:ci
      - run: npm run e2e
      - run: npx reg-cli test/visual/latest/digibytego test/visual/approved/digibytego test/visual/diffs --report test/visual/report.html --json test/visual/report.json --enableAntialias  --pixelThreshold 20
      - run: npx codecov
      - store_artifacts:
          path: ./test
      - store_test_results:
          path: ./test

  # Run tests using CircleCI's local CLI
  build:
    docker:
      - image: circleci/node:9-browsers
    working_directory: ~/digibytego
    steps:
      - checkout
      - run: npm install
      - run: npm rebuild node-sass
      - run: npm run apply:digibyte
      - run: npm run e2e
      - run: npm run test:visual
          
workflows:
  version: 2
  build_and_test:
    jobs:
      - digibytego